modLoader="javafml"
loaderVersion="${loader_version_range}"

license="All Rights Reserved"

[[mods]]
modId="diy_campfires"
version="1.0.0.0"
displayName="DIY Campfires"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
logoFile="diy-campfires-icon-static.png"
credits="MarbledHubb Studios"
authors="MarbledNull, WereF0X"

description='''A mod that adds a simple building mechanic to Campfires.'''

[[dependencies.diy_campfires]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.diy_campfires]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

